version: 1
accounts:
- name: alice
  coins:
  - 7777777test
- name: bob
  coins:
  - 7777777test
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 500test
validators:
- name: alice
  bonded: 7777777test
