version: 1
accounts:
- name: alice
  coins:
  - 7777777test
- name: bob
  coins:
  - 7777777test
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 500test
validators:
- name: alice
  bonded: 7777777test
genesis:
  app_state:
    staking:
      params:
        bond_denom: "test"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "test"
    crisis:
      constant_fee:
        denom: "test"
    mint:
      params:
        mint_denom: "test"
